#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\AnimationsView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "D765CA9699844301F51875600D839A5A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class AnimationsView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // AnimationsView.xaml line 13
                {
                    this.AddDelete = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.AddDelete).Click += this.navigateToControl;
                }
                break;
            case 2: // AnimationsView.xaml line 14
                {
                    this.ContentThemeTransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ContentThemeTransition).Click += this.navigateToControl;
                }
                break;
            case 3: // AnimationsView.xaml line 15
                {
                    this.EdgeUITransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.EdgeUITransition).Click += this.navigateToControl;
                }
                break;
            case 4: // AnimationsView.xaml line 16
                {
                    this.EntranceThemeTransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.EntranceThemeTransition).Click += this.navigateToControl;
                }
                break;
            case 5: // AnimationsView.xaml line 17
                {
                    this.PaneThemeTransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.PaneThemeTransition).Click += this.navigateToControl;
                }
                break;
            case 6: // AnimationsView.xaml line 18
                {
                    this.PopupThemeTransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.PopupThemeTransition).Click += this.navigateToControl;
                }
                break;
            case 7: // AnimationsView.xaml line 19
                {
                    this.ReorderThemeTransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ReorderThemeTransition).Click += this.navigateToControl;
                }
                break;
            case 8: // AnimationsView.xaml line 20
                {
                    this.RepositionThemeTransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.RepositionThemeTransition).Click += this.navigateToControl;
                }
                break;
            case 9: // AnimationsView.xaml line 23
                {
                    this.ContinuumNavTransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ContinuumNavTransition).Click += this.navigateToControl;
                }
                break;
            case 10: // AnimationsView.xaml line 24
                {
                    this.SlideNavTransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.SlideNavTransition).Click += this.navigateToControl;
                }
                break;
            case 11: // AnimationsView.xaml line 25
                {
                    this.TurnstileFeatheringNavTransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.TurnstileFeatheringNavTransition).Click += this.navigateToControl;
                }
                break;
            case 12: // AnimationsView.xaml line 26
                {
                    this.TurnstileNavTransition = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.TurnstileNavTransition).Click += this.navigateToControl;
                }
                break;
            case 13: // AnimationsView.xaml line 29
                {
                    this.ControlAnimations = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ControlAnimations).Click += this.navigateToControl;
                }
                break;
            case 14: // AnimationsView.xaml line 30
                {
                    this.ThemeAnimations = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ThemeAnimations).Click += this.navigateToControl;
                }
                break;
            case 15: // AnimationsView.xaml line 33
                {
                    this.ColorDoublePointAnimation = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ColorDoublePointAnimation).Click += this.navigateToControl;
                }
                break;
            case 16: // AnimationsView.xaml line 34
                {
                    this.EasingFunctions = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.EasingFunctions).Click += this.navigateToControl;
                }
                break;
            case 17: // AnimationsView.xaml line 35
                {
                    this.FromToByAnimations = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.FromToByAnimations).Click += this.navigateToControl;
                }
                break;
            case 18: // AnimationsView.xaml line 36
                {
                    this.KeyFramesAnimation = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.KeyFramesAnimation).Click += this.navigateToControl;
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

