#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\ButtonBaseView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "F825E642AFC02E65AAC48CF887B751D7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class ButtonBaseView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // ButtonBaseView.xaml line 53
                {
                    this.ToggleButton1 = (global::Windows.UI.Xaml.Controls.Primitives.ToggleButton)(target);
                }
                break;
            case 2: // ButtonBaseView.xaml line 54
                {
                    this.IsChecked2 = (global::Windows.UI.Xaml.Controls.CheckBox)(target);
                }
                break;
            case 3: // ButtonBaseView.xaml line 44
                {
                    this.RadioButton1 = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                }
                break;
            case 4: // ButtonBaseView.xaml line 45
                {
                    this.RadioButton2 = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                }
                break;
            case 5: // ButtonBaseView.xaml line 46
                {
                    this.RadioButton3 = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                }
                break;
            case 6: // ButtonBaseView.xaml line 36
                {
                    global::Windows.UI.Xaml.Controls.HyperlinkButton element6 = (global::Windows.UI.Xaml.Controls.HyperlinkButton)(target);
                    ((global::Windows.UI.Xaml.Controls.HyperlinkButton)element6).Click += this.HyperlinkButton_Click;
                }
                break;
            case 7: // ButtonBaseView.xaml line 37
                {
                    this.ClickMessage2 = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            case 8: // ButtonBaseView.xaml line 29
                {
                    this.CheckBox1 = (global::Windows.UI.Xaml.Controls.CheckBox)(target);
                }
                break;
            case 9: // ButtonBaseView.xaml line 30
                {
                    this.IsChecked = (global::Windows.UI.Xaml.Controls.CheckBox)(target);
                }
                break;
            case 10: // ButtonBaseView.xaml line 14
                {
                    global::Windows.UI.Xaml.Controls.Button element10 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element10).Click += this.Button_Click;
                }
                break;
            case 11: // ButtonBaseView.xaml line 15
                {
                    this.ClickMessage = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

