#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\ContentDialogView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "397151D85A3160E7E7EE76028237B86B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class ContentDialogView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // ContentDialogView.xaml line 12
                {
                    global::Windows.UI.Xaml.Controls.Button element1 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element1).Click += this.showWifiDialog;
                }
                break;
            case 2: // ContentDialogView.xaml line 13
                {
                    global::Windows.UI.Xaml.Controls.Button element2 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element2).Click += this.showWifiDialog;
                }
                break;
            case 3: // ContentDialogView.xaml line 14
                {
                    global::Windows.UI.Xaml.Controls.Button element3 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element3).Click += this.showXamlDialog;
                }
                break;
            case 4: // ContentDialogView.xaml line 16
                {
                    this.termsOfUseContentDialog = (global::Windows.UI.Xaml.Controls.ContentDialog)(target);
                    ((global::Windows.UI.Xaml.Controls.ContentDialog)this.termsOfUseContentDialog).Opened += this.TermsOfUseContentDialog_Opened;
                }
                break;
            case 5: // ContentDialogView.xaml line 54
                {
                    this.exOutput = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            case 6: // ContentDialogView.xaml line 48
                {
                    this.ConfirmAgeCheckBox = (global::Windows.UI.Xaml.Controls.CheckBox)(target);
                    ((global::Windows.UI.Xaml.Controls.CheckBox)this.ConfirmAgeCheckBox).Checked += this.ConfirmAgeCheckBox_Checked;
                    ((global::Windows.UI.Xaml.Controls.CheckBox)this.ConfirmAgeCheckBox).Unchecked += this.ConfirmAgeCheckBox_Unchecked;
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

