#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\DateTimePickerView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "CDDFF711CB887AB0A827128768292F92"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class DateTimePickerView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // DateTimePickerView.xaml line 13
                {
                    this.changeDate = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.changeDate).Click += this.changeDate_Click;
                }
                break;
            case 2: // DateTimePickerView.xaml line 14
                {
                    this.changeYearRange = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.changeYearRange).Click += this.changeYearRange_Click;
                }
                break;
            case 3: // DateTimePickerView.xaml line 15
                {
                    this.showDayOfWeek = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.showDayOfWeek).Click += this.showDayOfWeek_Click;
                }
                break;
            case 4: // DateTimePickerView.xaml line 16
                {
                    this.showMonthAsNumber = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.showMonthAsNumber).Click += this.showMonthAsNumber_Click;
                }
                break;
            case 5: // DateTimePickerView.xaml line 17
                {
                    this.toggleYear = (global::Windows.UI.Xaml.Controls.Primitives.ToggleButton)(target);
                    ((global::Windows.UI.Xaml.Controls.Primitives.ToggleButton)this.toggleYear).Checked += this.toggleYear_Update;
                    ((global::Windows.UI.Xaml.Controls.Primitives.ToggleButton)this.toggleYear).Unchecked += this.toggleYear_Update;
                }
                break;
            case 6: // DateTimePickerView.xaml line 18
                {
                    this.combine = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.combine).Click += this.combine_Click;
                }
                break;
            case 7: // DateTimePickerView.xaml line 19
                {
                    this.datePicker = (global::Windows.UI.Xaml.Controls.DatePicker)(target);
                }
                break;
            case 8: // DateTimePickerView.xaml line 20
                {
                    this.timePicker = (global::Windows.UI.Xaml.Controls.TimePicker)(target);
                }
                break;
            case 9: // DateTimePickerView.xaml line 21
                {
                    this.StatusBlock = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

