#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\EasingFunctionsView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "6FF68F963304595B67B95064160DD092"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class EasingFunctionsView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // EasingFunctionsView.xaml line 39
                {
                    this.storyboard = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 2: // EasingFunctionsView.xaml line 40
                {
                    this.RectanglePositionAnimation = (global::Windows.UI.Xaml.Media.Animation.DoubleAnimation)(target);
                }
                break;
            case 3: // EasingFunctionsView.xaml line 45
                {
                    this.GraphPositionMarkerXAnimation = (global::Windows.UI.Xaml.Media.Animation.DoubleAnimation)(target);
                }
                break;
            case 4: // EasingFunctionsView.xaml line 50
                {
                    this.GraphPositionMarkerYAnimation = (global::Windows.UI.Xaml.Media.Animation.DoubleAnimation)(target);
                }
                break;
            case 5: // EasingFunctionsView.xaml line 72
                {
                    this.MovingRectangle = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 6: // EasingFunctionsView.xaml line 58
                {
                    this.GraphContainer = (global::Windows.UI.Xaml.Controls.Canvas)(target);
                }
                break;
            case 7: // EasingFunctionsView.xaml line 62
                {
                    this.Graph = (global::Windows.UI.Xaml.Controls.Canvas)(target);
                }
                break;
            case 8: // EasingFunctionsView.xaml line 65
                {
                    this.GraphMarker = (global::Windows.UI.Xaml.Shapes.Ellipse)(target);
                }
                break;
            case 9: // EasingFunctionsView.xaml line 29
                {
                    this.EasingModeSelector = (global::Windows.UI.Xaml.Controls.ComboBox)(target);
                    ((global::Windows.UI.Xaml.Controls.ComboBox)this.EasingModeSelector).SelectionChanged += this.EasingFunctionChanged;
                }
                break;
            case 10: // EasingFunctionsView.xaml line 19
                {
                    this.FunctionSelector = (global::Windows.UI.Xaml.Controls.ComboBox)(target);
                    ((global::Windows.UI.Xaml.Controls.ComboBox)this.FunctionSelector).SelectionChanged += this.EasingFunctionChanged;
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

