#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\FromToByAnimationsView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "BC6FDE0742F9F6518D32F5266CA7DE5D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class FromToByAnimationsView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // FromToByAnimationsView.xaml line 22
                {
                    global::Windows.UI.Xaml.Controls.Button element1 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element1).Click += this.Seek1_Click;
                }
                break;
            case 2: // FromToByAnimationsView.xaml line 23
                {
                    global::Windows.UI.Xaml.Controls.Button element2 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element2).Click += this.Seek2_Click;
                }
                break;
            case 3: // FromToByAnimationsView.xaml line 24
                {
                    global::Windows.UI.Xaml.Controls.Button element3 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element3).Click += this.Seek3_Click;
                }
                break;
            case 4: // FromToByAnimationsView.xaml line 25
                {
                    global::Windows.UI.Xaml.Controls.Button element4 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element4).Click += this.Play_Click;
                }
                break;
            case 5: // FromToByAnimationsView.xaml line 29
                {
                    this.ColorAnimationTarget_From = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 6: // FromToByAnimationsView.xaml line 30
                {
                    this.DoubleAnimationTarget_From = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 7: // FromToByAnimationsView.xaml line 38
                {
                    this.ColorAnimationTarget_FromTo = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 8: // FromToByAnimationsView.xaml line 39
                {
                    this.DoubleAnimationTarget_FromTo = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 9: // FromToByAnimationsView.xaml line 47
                {
                    this.ColorAnimationTarget_FromBy = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 10: // FromToByAnimationsView.xaml line 48
                {
                    this.DoubleAnimationTarget_FromBy = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 11: // FromToByAnimationsView.xaml line 56
                {
                    this.ColorAnimationTarget_ToBy = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 12: // FromToByAnimationsView.xaml line 57
                {
                    this.DoubleAnimationTarget_ToBy = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 13: // FromToByAnimationsView.xaml line 65
                {
                    this.ColorAnimationTarget_To = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 14: // FromToByAnimationsView.xaml line 66
                {
                    this.DoubleAnimationTarget_To = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 15: // FromToByAnimationsView.xaml line 74
                {
                    this.ColorAnimationTarget_By = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 16: // FromToByAnimationsView.xaml line 75
                {
                    this.DoubleAnimationTarget_By = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 17: // FromToByAnimationsView.xaml line 78
                {
                    this.PointAnimationTarget_By = (global::Windows.UI.Xaml.Media.EllipseGeometry)(target);
                }
                break;
            case 18: // FromToByAnimationsView.xaml line 69
                {
                    this.PointAnimationTarget_To = (global::Windows.UI.Xaml.Media.EllipseGeometry)(target);
                }
                break;
            case 19: // FromToByAnimationsView.xaml line 60
                {
                    this.PointAnimationTarget_ToBy = (global::Windows.UI.Xaml.Media.EllipseGeometry)(target);
                }
                break;
            case 20: // FromToByAnimationsView.xaml line 51
                {
                    this.PointAnimationTarget_FromBy = (global::Windows.UI.Xaml.Media.EllipseGeometry)(target);
                }
                break;
            case 21: // FromToByAnimationsView.xaml line 42
                {
                    this.PointAnimationTarget_FromTo = (global::Windows.UI.Xaml.Media.EllipseGeometry)(target);
                }
                break;
            case 22: // FromToByAnimationsView.xaml line 33
                {
                    this.PointAnimationTarget_From = (global::Windows.UI.Xaml.Media.EllipseGeometry)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

