#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\KeyFramesAnimationView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "41A897989B50275B85644786B2E1942C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class KeyFramesAnimationView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // KeyFramesAnimationView.xaml line 22
                {
                    this.colorAnimationTargetRect = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 2: // KeyFramesAnimationView.xaml line 68
                {
                    this.pointAnimationTargetEllipse = (global::Windows.UI.Xaml.Media.EllipseGeometry)(target);
                }
                break;
            case 3: // KeyFramesAnimationView.xaml line 44
                {
                    this.doubleAnimationTargetRect = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

