#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\KeyTipsView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "F4F23EF2BCDE625F5608D62CD56CDF24"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class KeyTipsView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // KeyTipsView.xaml line 806
                {
                    this.MainCommandBar = (global::Windows.UI.Xaml.Controls.CommandBar)(target);
                }
                break;
            case 2: // KeyTipsView.xaml line 807
                {
                    this.GoBtn = (global::Windows.UI.Xaml.Controls.AppBarButton)(target);
                }
                break;
            case 3: // KeyTipsView.xaml line 808
                {
                    this.StopButton = (global::Windows.UI.Xaml.Controls.AppBarButton)(target);
                }
                break;
            case 4: // KeyTipsView.xaml line 810
                {
                    this.RefreshBtn = (global::Windows.UI.Xaml.Controls.AppBarButton)(target);
                }
                break;
            case 5: // KeyTipsView.xaml line 811
                {
                    this.BackButton = (global::Windows.UI.Xaml.Controls.AppBarButton)(target);
                }
                break;
            case 6: // KeyTipsView.xaml line 812
                {
                    this.ForwardButton = (global::Windows.UI.Xaml.Controls.AppBarButton)(target);
                }
                break;
            case 7: // KeyTipsView.xaml line 814
                {
                    this.FavoriteBtn = (global::Windows.UI.Xaml.Controls.AppBarToggleButton)(target);
                }
                break;
            case 8: // KeyTipsView.xaml line 816
                {
                    this.LikeButton = (global::Windows.UI.Xaml.Controls.AppBarToggleButton)(target);
                }
                break;
            case 9: // KeyTipsView.xaml line 817
                {
                    this.SettingsButton = (global::Windows.UI.Xaml.Controls.AppBarButton)(target);
                }
                break;
            case 10: // KeyTipsView.xaml line 798
                {
                    this.b7 = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 11: // KeyTipsView.xaml line 799
                {
                    this.b8 = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 12: // KeyTipsView.xaml line 800
                {
                    this.b9 = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 13: // KeyTipsView.xaml line 779
                {
                    this.A = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 14: // KeyTipsView.xaml line 780
                {
                    this.B = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 15: // KeyTipsView.xaml line 781
                {
                    this.C = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 16: // KeyTipsView.xaml line 782
                {
                    this.D = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 17: // KeyTipsView.xaml line 783
                {
                    this.E = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 18: // KeyTipsView.xaml line 784
                {
                    this.F = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 19: // KeyTipsView.xaml line 785
                {
                    this.G = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 20: // KeyTipsView.xaml line 786
                {
                    this.H = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 21: // KeyTipsView.xaml line 787
                {
                    this.I = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 22: // KeyTipsView.xaml line 788
                {
                    this.J = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 23: // KeyTipsView.xaml line 789
                {
                    this.K = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 24: // KeyTipsView.xaml line 790
                {
                    this.L = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 25: // KeyTipsView.xaml line 791
                {
                    this.M = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 26: // KeyTipsView.xaml line 792
                {
                    this.N = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 27: // KeyTipsView.xaml line 793
                {
                    this.O = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 28: // KeyTipsView.xaml line 768
                {
                    this.b4 = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 29: // KeyTipsView.xaml line 769
                {
                    this.b5 = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 30: // KeyTipsView.xaml line 770
                {
                    this.b6 = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

