#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\ProgressView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "82584ADEB2995A488E3D5190BA77D09F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class ProgressView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // ProgressView.xaml line 27
                {
                    this.ProgressState = (global::Windows.UI.Xaml.Controls.Slider)(target);
                }
                break;
            case 2: // ProgressView.xaml line 33
                {
                    this.RunningRB = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                }
                break;
            case 3: // ProgressView.xaml line 34
                {
                    this.PausedRB = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                }
                break;
            case 4: // ProgressView.xaml line 35
                {
                    this.ErrorRB = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

