#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\SemanticZoomView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "1C1B1DC1DCE6EB5094BCECFE7BA6B9C2"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class SemanticZoomView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // SemanticZoomView.xaml line 11
                {
                    this.ZovItemTemplate = (global::Windows.UI.Xaml.DataTemplate)(target);
                }
                break;
            case 2: // SemanticZoomView.xaml line 24
                {
                    this.ZivItemTemplate = (global::Windows.UI.Xaml.DataTemplate)(target);
                }
                break;
            case 3: // SemanticZoomView.xaml line 35
                {
                    this.ZivHeaderTemplate = (global::Windows.UI.Xaml.DataTemplate)(target);
                }
                break;
            case 4: // SemanticZoomView.xaml line 48
                {
                    this.cvs = (global::Windows.UI.Xaml.Data.CollectionViewSource)(target);
                }
                break;
            case 5: // SemanticZoomView.xaml line 51
                {
                    this.semanticZoom = (global::Windows.UI.Xaml.Controls.SemanticZoom)(target);
                }
                break;
            case 6: // SemanticZoomView.xaml line 55
                {
                    this.jumpZov = (global::Windows.UI.Xaml.Controls.GridView)(target);
                }
                break;
            case 7: // SemanticZoomView.xaml line 63
                {
                    this.jumpZiv = (global::Windows.UI.Xaml.Controls.ListView)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

