#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\SplitView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "418924492946D4D8B5BE76A5F7DA5315"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class SplitView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // SplitView.xaml line 22
                {
                    this.splitView = (global::Windows.UI.Xaml.Controls.SplitView)(target);
                    ((global::Windows.UI.Xaml.Controls.SplitView)this.splitView).Loaded += this.SplitView_Loaded;
                }
                break;
            case 2: // SplitView.xaml line 77
                {
                    this.togglePaneButton = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.togglePaneButton).Click += this.togglePaneButton_Click;
                }
                break;
            case 3: // SplitView.xaml line 37
                {
                    this.paneHeader = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            case 4: // SplitView.xaml line 57
                {
                    this.headerrow = (global::Windows.UI.Xaml.Controls.RowDefinition)(target);
                }
                break;
            case 5: // SplitView.xaml line 58
                {
                    this.body = (global::Windows.UI.Xaml.Controls.RowDefinition)(target);
                }
                break;
            case 6: // SplitView.xaml line 68
                {
                    this.ContentFrame = (global::Windows.UI.Xaml.Controls.Frame)(target);
                }
                break;
            case 7: // SplitView.xaml line 17
                {
                    global::Windows.UI.Xaml.Controls.RadioButton element7 = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                    ((global::Windows.UI.Xaml.Controls.RadioButton)element7).Checked += this.DisplayModeRadioButtonChecked;
                }
                break;
            case 8: // SplitView.xaml line 18
                {
                    global::Windows.UI.Xaml.Controls.RadioButton element8 = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                    ((global::Windows.UI.Xaml.Controls.RadioButton)element8).Checked += this.DisplayModeRadioButtonChecked;
                }
                break;
            case 9: // SplitView.xaml line 19
                {
                    global::Windows.UI.Xaml.Controls.RadioButton element9 = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                    ((global::Windows.UI.Xaml.Controls.RadioButton)element9).Checked += this.DisplayModeRadioButtonChecked;
                }
                break;
            case 10: // SplitView.xaml line 20
                {
                    global::Windows.UI.Xaml.Controls.RadioButton element10 = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                    ((global::Windows.UI.Xaml.Controls.RadioButton)element10).Checked += this.DisplayModeRadioButtonChecked;
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

