#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\SuperJupiterHomeView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "CB2DC5AC4C634FE74B5D9E78B2FE68A0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class SuperJupiterHomeView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // SuperJupiterHomeView.xaml line 12
                {
                    this.optionsPanel = (global::Windows.UI.Xaml.Controls.StackPanel)(target);
                }
                break;
            case 2: // SuperJupiterHomeView.xaml line 13
                {
                    this.Animations = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Animations).Click += this.navigateToControl;
                }
                break;
            case 3: // SuperJupiterHomeView.xaml line 14
                {
                    this.AutoFocusTraps = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.AutoFocusTraps).Click += this.navigateToControl;
                }
                break;
            case 4: // SuperJupiterHomeView.xaml line 15
                {
                    this.BindingTest = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.BindingTest).Click += this.navigateToControl;
                }
                break;
            case 5: // SuperJupiterHomeView.xaml line 16
                {
                    this.ButtonBase = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ButtonBase).Click += this.navigateToControl;
                }
                break;
            case 6: // SuperJupiterHomeView.xaml line 17
                {
                    this.CaptureElement = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.CaptureElement).Click += this.navigateToControl;
                }
                break;
            case 7: // SuperJupiterHomeView.xaml line 18
                {
                    this.CalendarPicker = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.CalendarPicker).Click += this.navigateToControl;
                }
                break;
            case 8: // SuperJupiterHomeView.xaml line 19
                {
                    this.ComboBox = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ComboBox).Click += this.navigateToControl;
                }
                break;
            case 9: // SuperJupiterHomeView.xaml line 20
                {
                    this.CommandBar = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.CommandBar).Click += this.navigateToControl;
                }
                break;
            case 10: // SuperJupiterHomeView.xaml line 21
                {
                    this.ComponentUI = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ComponentUI).Click += this.navigateToControl;
                }
                break;
            case 11: // SuperJupiterHomeView.xaml line 22
                {
                    this.ContentDialog = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ContentDialog).Click += this.navigateToControl;
                }
                break;
            case 12: // SuperJupiterHomeView.xaml line 23
                {
                    this.DateTimePicker = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.DateTimePicker).Click += this.navigateToControl;
                }
                break;
            case 13: // SuperJupiterHomeView.xaml line 24
                {
                    this.Flip = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Flip).Click += this.navigateToControl;
                }
                break;
            case 14: // SuperJupiterHomeView.xaml line 25
                {
                    this.Flyouts = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Flyouts).Click += this.navigateToControl;
                }
                break;
            case 15: // SuperJupiterHomeView.xaml line 26
                {
                    this.FocusEngagement = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.FocusEngagement).Click += this.navigateToControl;
                }
                break;
            case 16: // SuperJupiterHomeView.xaml line 27
                {
                    this.FocusedElementRemoved = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.FocusedElementRemoved).Click += this.navigateToControl;
                }
                break;
            case 17: // SuperJupiterHomeView.xaml line 28
                {
                    this.Hub = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Hub).Click += this.navigateToControl;
                }
                break;
            case 18: // SuperJupiterHomeView.xaml line 29
                {
                    this.Image = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Image).Click += this.navigateToControl;
                }
                break;
            case 19: // SuperJupiterHomeView.xaml line 30
                {
                    this.KeyTips = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.KeyTips).Click += this.navigateToControl;
                }
                break;
            case 20: // SuperJupiterHomeView.xaml line 31
                {
                    this.ListViewBase = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ListViewBase).Click += this.navigateToControl;
                }
                break;
            case 21: // SuperJupiterHomeView.xaml line 32
                {
                    this.Maps = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Maps).Click += this.navigateToControl;
                }
                break;
            case 22: // SuperJupiterHomeView.xaml line 33
                {
                    this.Media = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Media).Click += this.navigateToControl;
                }
                break;
            case 23: // SuperJupiterHomeView.xaml line 34
                {
                    this.MediaPlayer = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.MediaPlayer).Click += this.navigateToControl;
                }
                break;
            case 24: // SuperJupiterHomeView.xaml line 35
                {
                    this.MessageDialog = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.MessageDialog).Click += this.navigateToControl;
                }
                break;
            case 25: // SuperJupiterHomeView.xaml line 36
                {
                    this.Pivot = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Pivot).Click += this.navigateToControl;
                }
                break;
            case 26: // SuperJupiterHomeView.xaml line 37
                {
                    this.PopupBase = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.PopupBase).Click += this.navigateToControl;
                }
                break;
            case 27: // SuperJupiterHomeView.xaml line 38
                {
                    this.Progress = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Progress).Click += this.navigateToControl;
                }
                break;
            case 28: // SuperJupiterHomeView.xaml line 39
                {
                    this.RelativeLayout = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.RelativeLayout).Click += this.navigateToControl;
                }
                break;
            case 29: // SuperJupiterHomeView.xaml line 40
                {
                    this.ScrollViewer = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.ScrollViewer).Click += this.navigateToControl;
                }
                break;
            case 30: // SuperJupiterHomeView.xaml line 41
                {
                    this.SemanticZoom = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.SemanticZoom).Click += this.navigateToControl;
                }
                break;
            case 31: // SuperJupiterHomeView.xaml line 42
                {
                    this.Split = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Split).Click += this.navigateToControl;
                }
                break;
            case 32: // SuperJupiterHomeView.xaml line 43
                {
                    this.SwapChainPanel = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.SwapChainPanel).Click += this.navigateToControl;
                }
                break;
            case 33: // SuperJupiterHomeView.xaml line 44
                {
                    this.Text = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Text).Click += this.navigateToControl;
                }
                break;
            case 34: // SuperJupiterHomeView.xaml line 45
                {
                    this.TextBox = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.TextBox).Click += this.navigateToControl;
                }
                break;
            case 35: // SuperJupiterHomeView.xaml line 46
                {
                    this.Tooltip = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Tooltip).Click += this.navigateToControl;
                }
                break;
            case 36: // SuperJupiterHomeView.xaml line 47
                {
                    this.Web = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.Web).Click += this.navigateToControl;
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

