#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\TextView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "285F5B83707F1F328B42BD82957C1150"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class TextView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // TextView.xaml line 47
                {
                    global::Windows.UI.Xaml.Controls.Button element1 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element1).Click += this.toggleVisibility;
                }
                break;
            case 2: // TextView.xaml line 48
                {
                    this.typography = (global::Windows.UI.Xaml.Controls.Grid)(target);
                }
                break;
            case 3: // TextView.xaml line 101
                {
                    global::Windows.UI.Xaml.Controls.Button element3 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element3).Click += this.toggleVisibility;
                }
                break;
            case 4: // TextView.xaml line 102
                {
                    this.fractions = (global::Windows.UI.Xaml.Controls.StackPanel)(target);
                }
                break;
            case 5: // TextView.xaml line 110
                {
                    global::Windows.UI.Xaml.Controls.Button element5 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element5).Click += this.toggleVisibility;
                }
                break;
            case 6: // TextView.xaml line 111
                {
                    this.subSuperScript = (global::Windows.UI.Xaml.Controls.StackPanel)(target);
                }
                break;
            case 7: // TextView.xaml line 120
                {
                    global::Windows.UI.Xaml.Controls.Button element7 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element7).Click += this.toggleVisibility;
                }
                break;
            case 8: // TextView.xaml line 121
                {
                    this.historicalForms = (global::Windows.UI.Xaml.Controls.StackPanel)(target);
                }
                break;
            case 9: // TextView.xaml line 129
                {
                    global::Windows.UI.Xaml.Controls.Button element9 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element9).Click += this.toggleVisibility;
                }
                break;
            case 10: // TextView.xaml line 130
                {
                    this.stylisticSets = (global::Windows.UI.Xaml.Controls.StackPanel)(target);
                }
                break;
            case 11: // TextView.xaml line 140
                {
                    global::Windows.UI.Xaml.Controls.Button element11 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element11).Click += this.toggleVisibility;
                }
                break;
            case 12: // TextView.xaml line 141
                {
                    this.Ligatures = (global::Windows.UI.Xaml.Controls.StackPanel)(target);
                }
                break;
            case 13: // TextView.xaml line 179
                {
                    this.tbHyperlinkClicked = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            case 14: // TextView.xaml line 182
                {
                    global::Windows.UI.Xaml.Documents.Hyperlink element14 = (global::Windows.UI.Xaml.Documents.Hyperlink)(target);
                    ((global::Windows.UI.Xaml.Documents.Hyperlink)element14).Click += this.Hyperlink_Click;
                }
                break;
            case 15: // TextView.xaml line 161
                {
                    this.fontSizeSlider = (global::Windows.UI.Xaml.Controls.Slider)(target);
                }
                break;
            case 16: // TextView.xaml line 163
                {
                    this.columnGrid = (global::Windows.UI.Xaml.Controls.Grid)(target);
                }
                break;
            case 17: // TextView.xaml line 173
                {
                    this.firstOverflowContainer = (global::Windows.UI.Xaml.Controls.RichTextBlockOverflow)(target);
                }
                break;
            case 18: // TextView.xaml line 37
                {
                    this.baselineToBaselineTextBlock = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            case 19: // TextView.xaml line 31
                {
                    this.lineHeightSlider = (global::Windows.UI.Xaml.Controls.Slider)(target);
                }
                break;
            case 20: // TextView.xaml line 25
                {
                    global::Windows.UI.Xaml.Controls.RadioButton element20 = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                    ((global::Windows.UI.Xaml.Controls.RadioButton)element20).Checked += this.changeLineStacking;
                }
                break;
            case 21: // TextView.xaml line 26
                {
                    global::Windows.UI.Xaml.Controls.RadioButton element21 = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                    ((global::Windows.UI.Xaml.Controls.RadioButton)element21).Checked += this.changeLineStacking;
                }
                break;
            case 22: // TextView.xaml line 27
                {
                    global::Windows.UI.Xaml.Controls.RadioButton element22 = (global::Windows.UI.Xaml.Controls.RadioButton)(target);
                    ((global::Windows.UI.Xaml.Controls.RadioButton)element22).Checked += this.changeLineStacking;
                }
                break;
            case 23: // TextView.xaml line 15
                {
                    this.characterSpacingSlider = (global::Windows.UI.Xaml.Controls.Slider)(target);
                }
                break;
            case 24: // TextView.xaml line 16
                {
                    this.characterSpacingTextBlock = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

