#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\TextBoxView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "F8FFEAF84EB35D060F221B9EF7386329"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class TextBoxView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // TextBoxView.xaml line 128
                {
                    this.editor = (global::Windows.UI.Xaml.Controls.RichEditBox)(target);
                }
                break;
            case 2: // TextBoxView.xaml line 158
                {
                    this.textEventsLoggingScrollViewer = (global::Windows.UI.Xaml.Controls.ScrollViewer)(target);
                }
                break;
            case 3: // TextBoxView.xaml line 159
                {
                    this.textEventsLoggingTB = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            case 4: // TextBoxView.xaml line 155
                {
                    this.textEventsTB = (global::Windows.UI.Xaml.Controls.TextBox)(target);
                    ((global::Windows.UI.Xaml.Controls.TextBox)this.textEventsTB).TextChanged += this.textEventsTB_TextChanged;
                    ((global::Windows.UI.Xaml.Controls.TextBox)this.textEventsTB).TextChanging += this.textEventsTB_TextChanging;
                    ((global::Windows.UI.Xaml.Controls.TextBox)this.textEventsTB).TextCompositionStarted += this.textEventsTB_TextCompositionStarted;
                    ((global::Windows.UI.Xaml.Controls.TextBox)this.textEventsTB).TextCompositionChanged += this.textEventsTB_TextCompositionChanged;
                    ((global::Windows.UI.Xaml.Controls.TextBox)this.textEventsTB).TextCompositionEnded += this.textEventsTB_TextCompositionEnded;
                }
                break;
            case 5: // TextBoxView.xaml line 144
                {
                    this.passwordBoxNumericPin = (global::Windows.UI.Xaml.Controls.PasswordBox)(target);
                }
                break;
            case 6: // TextBoxView.xaml line 134
                {
                    this.passwordBox = (global::Windows.UI.Xaml.Controls.PasswordBox)(target);
                }
                break;
            case 7: // TextBoxView.xaml line 126
                {
                    this.findBox = (global::Windows.UI.Xaml.Controls.TextBox)(target);
                    ((global::Windows.UI.Xaml.Controls.TextBox)this.findBox).TextChanged += this.FindBoxTextChanged;
                    ((global::Windows.UI.Xaml.Controls.TextBox)this.findBox).GotFocus += this.FindBoxGotFocus;
                    ((global::Windows.UI.Xaml.Controls.TextBox)this.findBox).LostFocus += this.FindBoxLostFocus;
                }
                break;
            case 8: // TextBoxView.xaml line 78
                {
                    global::Windows.UI.Xaml.Controls.Button element8 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element8).Click += this.BoldButtonClick;
                }
                break;
            case 9: // TextBoxView.xaml line 79
                {
                    global::Windows.UI.Xaml.Controls.Button element9 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element9).Click += this.ItalicButtonClick;
                }
                break;
            case 10: // TextBoxView.xaml line 80
                {
                    this.fontColorGrid = (global::Windows.UI.Xaml.Controls.Grid)(target);
                }
                break;
            case 11: // TextBoxView.xaml line 81
                {
                    this.fontColorButton = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.fontColorButton).Click += this.FontColorButtonClick;
                    ((global::Windows.UI.Xaml.Controls.Button)this.fontColorButton).LostFocus += this.FontColorButtonLostFocus;
                }
                break;
            case 12: // TextBoxView.xaml line 82
                {
                    this.fontColorPopup = (global::Windows.UI.Xaml.Controls.Primitives.Popup)(target);
                }
                break;
            case 13: // TextBoxView.xaml line 94
                {
                    this.black = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.black).Click += this.ColorButtonClick;
                }
                break;
            case 14: // TextBoxView.xaml line 99
                {
                    this.gray = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.gray).Click += this.ColorButtonClick;
                }
                break;
            case 15: // TextBoxView.xaml line 104
                {
                    this.darkgreen = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.darkgreen).Click += this.ColorButtonClick;
                }
                break;
            case 16: // TextBoxView.xaml line 109
                {
                    this.green = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.green).Click += this.ColorButtonClick;
                }
                break;
            case 17: // TextBoxView.xaml line 114
                {
                    this.blue = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.blue).Click += this.ColorButtonClick;
                }
                break;
            case 18: // TextBoxView.xaml line 119
                {
                    global::Windows.UI.Xaml.Controls.Button element18 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element18).Click += this.ColorButtonClick;
                }
                break;
            case 19: // TextBoxView.xaml line 54
                {
                    this.inputScopeBox4 = (global::Windows.UI.Xaml.Controls.TextBox)(target);
                }
                break;
            case 20: // TextBoxView.xaml line 49
                {
                    this.inputScopeBox3 = (global::Windows.UI.Xaml.Controls.TextBox)(target);
                }
                break;
            case 21: // TextBoxView.xaml line 44
                {
                    this.inputScopeBox2 = (global::Windows.UI.Xaml.Controls.TextBox)(target);
                }
                break;
            case 22: // TextBoxView.xaml line 39
                {
                    this.inputScopeBox = (global::Windows.UI.Xaml.Controls.TextBox)(target);
                }
                break;
            case 23: // TextBoxView.xaml line 27
                {
                    this.ContentText2 = (global::Windows.UI.Xaml.Controls.TextBox)(target);
                }
                break;
            case 24: // TextBoxView.xaml line 15
                {
                    this.ContentText = (global::Windows.UI.Xaml.Controls.TextBox)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

