#pragma checksum "C:\projects\WPFSuperJupiter\SuperJupiterViews\ThemeAnimationsView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "775BC366C60DCC3AB21C7824CCF54B35"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperJupiter.Views
{
    partial class ThemeAnimationsView : 
        global::Windows.UI.Xaml.Controls.Page, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1: // ThemeAnimationsView.xaml line 54
                {
                    this.hostCanvas = (global::Windows.UI.Xaml.Controls.Canvas)(target);
                }
                break;
            case 2: // ThemeAnimationsView.xaml line 56
                {
                    this.dragitem = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 3: // ThemeAnimationsView.xaml line 57
                {
                    this.dragover = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 4: // ThemeAnimationsView.xaml line 58
                {
                    this.droptargetitem = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 5: // ThemeAnimationsView.xaml line 59
                {
                    this.reposition = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 6: // ThemeAnimationsView.xaml line 60
                {
                    this.fadein = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 7: // ThemeAnimationsView.xaml line 61
                {
                    this.fadeout = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 8: // ThemeAnimationsView.xaml line 62
                {
                    this.pointerup = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 9: // ThemeAnimationsView.xaml line 63
                {
                    this.pointerdown = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 10: // ThemeAnimationsView.xaml line 64
                {
                    this.popin = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 11: // ThemeAnimationsView.xaml line 65
                {
                    this.popout = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 12: // ThemeAnimationsView.xaml line 66
                {
                    this.splitopen = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 13: // ThemeAnimationsView.xaml line 67
                {
                    this.splitclose = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 14: // ThemeAnimationsView.xaml line 68
                {
                    this.swipeback = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 15: // ThemeAnimationsView.xaml line 69
                {
                    this.swipehint = (global::Windows.UI.Xaml.Media.Animation.Storyboard)(target);
                }
                break;
            case 16: // ThemeAnimationsView.xaml line 72
                {
                    this.rectangle = (global::Windows.UI.Xaml.Shapes.Rectangle)(target);
                }
                break;
            case 17: // ThemeAnimationsView.xaml line 92
                {
                    this.popup = (global::Windows.UI.Xaml.Controls.Primitives.Popup)(target);
                }
                break;
            case 18: // ThemeAnimationsView.xaml line 93
                {
                    this.border = (global::Windows.UI.Xaml.Controls.Border)(target);
                }
                break;
            case 19: // ThemeAnimationsView.xaml line 94
                {
                    this.listbox = (global::Windows.UI.Xaml.Controls.ListBox)(target);
                }
                break;
            case 20: // ThemeAnimationsView.xaml line 48
                {
                    global::Windows.UI.Xaml.Controls.Button element20 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element20).Click += this.SwipeBackThemeAnimation_Click;
                }
                break;
            case 21: // ThemeAnimationsView.xaml line 49
                {
                    global::Windows.UI.Xaml.Controls.Button element21 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element21).Click += this.SwipeHintThemeAnimation_Click;
                }
                break;
            case 22: // ThemeAnimationsView.xaml line 43
                {
                    this.splitOpenBtn = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.splitOpenBtn).Click += this.SplitOpenThemeAnimation_Click;
                }
                break;
            case 23: // ThemeAnimationsView.xaml line 44
                {
                    this.splitCloseBtn = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.splitCloseBtn).Click += this.SplitCloseThemeAnimation_Click;
                }
                break;
            case 24: // ThemeAnimationsView.xaml line 38
                {
                    global::Windows.UI.Xaml.Controls.Button element24 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element24).Click += this.PopInThemeAnimation_Click;
                }
                break;
            case 25: // ThemeAnimationsView.xaml line 39
                {
                    global::Windows.UI.Xaml.Controls.Button element25 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element25).Click += this.PopOutThemeAnimation_Click;
                }
                break;
            case 26: // ThemeAnimationsView.xaml line 33
                {
                    global::Windows.UI.Xaml.Controls.Button element26 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element26).Click += this.PointerDownThemeAnimation_Click;
                }
                break;
            case 27: // ThemeAnimationsView.xaml line 34
                {
                    global::Windows.UI.Xaml.Controls.Button element27 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element27).Click += this.PointerUpThemeAnimation_Click;
                }
                break;
            case 28: // ThemeAnimationsView.xaml line 28
                {
                    global::Windows.UI.Xaml.Controls.Button element28 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element28).Click += this.FadeInThemeAnimation_Click;
                }
                break;
            case 29: // ThemeAnimationsView.xaml line 29
                {
                    global::Windows.UI.Xaml.Controls.Button element29 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element29).Click += this.FadeOutThemeAnimation_Click;
                }
                break;
            case 30: // ThemeAnimationsView.xaml line 23
                {
                    global::Windows.UI.Xaml.Controls.Button element30 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element30).Click += this.DropTargetItemThemeAnimation_Click;
                }
                break;
            case 31: // ThemeAnimationsView.xaml line 24
                {
                    global::Windows.UI.Xaml.Controls.Button element31 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element31).Click += this.RepositionThemeAnimation_Click;
                }
                break;
            case 32: // ThemeAnimationsView.xaml line 18
                {
                    global::Windows.UI.Xaml.Controls.Button element32 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element32).Click += this.DragItemThemeAnimation_Click;
                }
                break;
            case 33: // ThemeAnimationsView.xaml line 19
                {
                    global::Windows.UI.Xaml.Controls.Button element33 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element33).Click += this.DragOverThemeAnimation_Click;
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

