//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace SuperJupiterViews.SuperJupiterViews_XamlTypeInfo
{
    /// <summary>
    /// Main class for providing metadata for the app or library
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class XamlMetaDataProvider : global::Windows.UI.Xaml.Markup.IXamlMetadataProvider
    {
        private global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlTypeInfoProvider _provider = null;

        private global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlTypeInfoProvider Provider
        {
            get
            {
                if (_provider == null)
                {
                    _provider = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlTypeInfoProvider();
                }
                return _provider;
            }
        }

        /// <summary>
        /// GetXamlType(Type)
        /// </summary>
        public global::Windows.UI.Xaml.Markup.IXamlType GetXamlType(global::System.Type type)
        {
            return Provider.GetXamlTypeByType(type);
        }

        /// <summary>
        /// GetXamlType(String)
        /// </summary>
        public global::Windows.UI.Xaml.Markup.IXamlType GetXamlType(string fullName)
        {
            return Provider.GetXamlTypeByName(fullName);
        }

        /// <summary>
        /// GetXmlnsDefinitions()
        /// </summary>
        public global::Windows.UI.Xaml.Markup.XmlnsDefinition[] GetXmlnsDefinitions()
        {
            return new global::Windows.UI.Xaml.Markup.XmlnsDefinition[0];
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal partial class XamlTypeInfoProvider
    {
        public global::Windows.UI.Xaml.Markup.IXamlType GetXamlTypeByType(global::System.Type type)
        {
            global::Windows.UI.Xaml.Markup.IXamlType xamlType;
            if (_xamlTypeCacheByType.TryGetValue(type, out xamlType))
            {
                return xamlType;
            }
            int typeIndex = LookupTypeIndexByType(type);
            if(typeIndex != -1)
            {
                xamlType = CreateXamlType(typeIndex);
            }
            if (xamlType != null)
            {
                _xamlTypeCacheByName.Add(xamlType.FullName, xamlType);
                _xamlTypeCacheByType.Add(xamlType.UnderlyingType, xamlType);
            }
            return xamlType;
        }

        public global::Windows.UI.Xaml.Markup.IXamlType GetXamlTypeByName(string typeName)
        {
            if (string.IsNullOrEmpty(typeName))
            {
                return null;
            }
            global::Windows.UI.Xaml.Markup.IXamlType xamlType;
            if (_xamlTypeCacheByName.TryGetValue(typeName, out xamlType))
            {
                return xamlType;
            }
            int typeIndex = LookupTypeIndexByName(typeName);
            if(typeIndex != -1)
            {
                xamlType = CreateXamlType(typeIndex);
            }
            if (xamlType != null)
            {
                _xamlTypeCacheByName.Add(xamlType.FullName, xamlType);
                _xamlTypeCacheByType.Add(xamlType.UnderlyingType, xamlType);
            }
            return xamlType;
        }

        public global::Windows.UI.Xaml.Markup.IXamlMember GetMemberByLongName(string longMemberName)
        {
            if (string.IsNullOrEmpty(longMemberName))
            {
                return null;
            }
            global::Windows.UI.Xaml.Markup.IXamlMember xamlMember;
            if (_xamlMembers.TryGetValue(longMemberName, out xamlMember))
            {
                return xamlMember;
            }
            xamlMember = CreateXamlMember(longMemberName);
            if (xamlMember != null)
            {
                _xamlMembers.Add(longMemberName, xamlMember);
            }
            return xamlMember;
        }

        global::System.Collections.Generic.Dictionary<string, global::Windows.UI.Xaml.Markup.IXamlType>
                _xamlTypeCacheByName = new global::System.Collections.Generic.Dictionary<string, global::Windows.UI.Xaml.Markup.IXamlType>();

        global::System.Collections.Generic.Dictionary<global::System.Type, global::Windows.UI.Xaml.Markup.IXamlType>
                _xamlTypeCacheByType = new global::System.Collections.Generic.Dictionary<global::System.Type, global::Windows.UI.Xaml.Markup.IXamlType>();

        global::System.Collections.Generic.Dictionary<string, global::Windows.UI.Xaml.Markup.IXamlMember>
                _xamlMembers = new global::System.Collections.Generic.Dictionary<string, global::Windows.UI.Xaml.Markup.IXamlMember>();

        string[] _typeNameTable = null;
        global::System.Type[] _typeTable = null;

        private void InitTypeTables()
        {
            _typeNameTable = new string[60];
            _typeNameTable[0] = "SuperJupiter.Views.AddDeleteView";
            _typeNameTable[1] = "Windows.UI.Xaml.Controls.Page";
            _typeNameTable[2] = "Windows.UI.Xaml.Controls.UserControl";
            _typeNameTable[3] = "SuperJupiter.Views.AnimationsView";
            _typeNameTable[4] = "SuperJupiter.Views.AutoFocusTrapsView";
            _typeNameTable[5] = "SuperJupiter.Views.BindingTestView";
            _typeNameTable[6] = "SuperJupiter.Views.ButtonBaseView";
            _typeNameTable[7] = "SuperJupiter.Views.CalendarPickerView";
            _typeNameTable[8] = "SuperJupiter.Views.CaptureElementView";
            _typeNameTable[9] = "SuperJupiter.Views.ColorDoublePointAnimationView";
            _typeNameTable[10] = "SuperJupiter.Views.ComboBoxView";
            _typeNameTable[11] = "SuperJupiter.Views.CommandBarView";
            _typeNameTable[12] = "SuperJupiter.Views.ContentDialogView";
            _typeNameTable[13] = "SuperJupiter.Views.ContentThemeTransitionView";
            _typeNameTable[14] = "SuperJupiter.Views.ContinuumNavTransitionView";
            _typeNameTable[15] = "System.Collections.Generic.List`1<String>";
            _typeNameTable[16] = "Object";
            _typeNameTable[17] = "String";
            _typeNameTable[18] = "SuperJupiter.Views.ControlAnimationsView";
            _typeNameTable[19] = "SuperJupiter.Views.DateTimePickerView";
            _typeNameTable[20] = "SuperJupiter.Views.EasingFunctionsView";
            _typeNameTable[21] = "SuperJupiter.Views.EdgeUITransitionView";
            _typeNameTable[22] = "SuperJupiter.Views.EntranceThemeTransitionView";
            _typeNameTable[23] = "SuperJupiter.Views.FlipView";
            _typeNameTable[24] = "SuperJupiter.Views.FlyoutsView";
            _typeNameTable[25] = "Boolean";
            _typeNameTable[26] = "SuperJupiter.Views.FocusedElementRemovedView";
            _typeNameTable[27] = "SuperJupiter.Views.FocusEngagementView";
            _typeNameTable[28] = "SuperJupiter.Views.FromToByAnimationsView";
            _typeNameTable[29] = "SuperJupiter.Views.HubView";
            _typeNameTable[30] = "SuperJupiter.Views.ImageView";
            _typeNameTable[31] = "SuperJupiter.Views.KeyFramesAnimationView";
            _typeNameTable[32] = "SuperJupiter.Views.KeyTipsView";
            _typeNameTable[33] = "SuperJupiter.Views.ListViewBaseView";
            _typeNameTable[34] = "SuperJupiter.MainPage";
            _typeNameTable[35] = "SuperJupiter.Views.MapsView";
            _typeNameTable[36] = "SuperJupiter.Views.MediaPlayerView";
            _typeNameTable[37] = "SuperJupiter.Views.MediaView";
            _typeNameTable[38] = "SuperJupiter.Views.MessageDialogView";
            _typeNameTable[39] = "SuperJupiter.Views.PaneThemeTransitionView";
            _typeNameTable[40] = "SuperJupiter.Views.PivotView";
            _typeNameTable[41] = "SuperJupiter.Views.PopupThemeTransitionView";
            _typeNameTable[42] = "SuperJupiter.Views.PopupBaseView";
            _typeNameTable[43] = "SuperJupiter.Views.ProgressView";
            _typeNameTable[44] = "SuperJupiter.Views.RelativeLayoutView";
            _typeNameTable[45] = "SuperJupiter.Views.ReorderThemeTransitionView";
            _typeNameTable[46] = "SuperJupiter.Views.RepositionThemeTransitionView";
            _typeNameTable[47] = "SuperJupiter.Views.ScrollViewerView";
            _typeNameTable[48] = "SuperJupiter.Views.SemanticZoomView";
            _typeNameTable[49] = "SuperJupiter.Views.SlideNavTransitionView";
            _typeNameTable[50] = "SuperJupiter.Views.SplitView";
            _typeNameTable[51] = "SuperJupiter.Views.SuperJupiterHomeView";
            _typeNameTable[52] = "SuperJupiterViews.TestUserControl";
            _typeNameTable[53] = "SuperJupiter.Views.TextBoxView";
            _typeNameTable[54] = "SuperJupiter.Views.TextView";
            _typeNameTable[55] = "SuperJupiter.Views.ThemeAnimationsView";
            _typeNameTable[56] = "SuperJupiter.Views.TooltipView";
            _typeNameTable[57] = "SuperJupiter.Views.TurnstileFeatheringNavTransitionView";
            _typeNameTable[58] = "SuperJupiter.Views.TurnstileNavTransitionView";
            _typeNameTable[59] = "SuperJupiter.Views.WebView";

            _typeTable = new global::System.Type[60];
            _typeTable[0] = typeof(global::SuperJupiter.Views.AddDeleteView);
            _typeTable[1] = typeof(global::Windows.UI.Xaml.Controls.Page);
            _typeTable[2] = typeof(global::Windows.UI.Xaml.Controls.UserControl);
            _typeTable[3] = typeof(global::SuperJupiter.Views.AnimationsView);
            _typeTable[4] = typeof(global::SuperJupiter.Views.AutoFocusTrapsView);
            _typeTable[5] = typeof(global::SuperJupiter.Views.BindingTestView);
            _typeTable[6] = typeof(global::SuperJupiter.Views.ButtonBaseView);
            _typeTable[7] = typeof(global::SuperJupiter.Views.CalendarPickerView);
            _typeTable[8] = typeof(global::SuperJupiter.Views.CaptureElementView);
            _typeTable[9] = typeof(global::SuperJupiter.Views.ColorDoublePointAnimationView);
            _typeTable[10] = typeof(global::SuperJupiter.Views.ComboBoxView);
            _typeTable[11] = typeof(global::SuperJupiter.Views.CommandBarView);
            _typeTable[12] = typeof(global::SuperJupiter.Views.ContentDialogView);
            _typeTable[13] = typeof(global::SuperJupiter.Views.ContentThemeTransitionView);
            _typeTable[14] = typeof(global::SuperJupiter.Views.ContinuumNavTransitionView);
            _typeTable[15] = typeof(global::System.Collections.Generic.List<global::System.String>);
            _typeTable[16] = typeof(global::System.Object);
            _typeTable[17] = typeof(global::System.String);
            _typeTable[18] = typeof(global::SuperJupiter.Views.ControlAnimationsView);
            _typeTable[19] = typeof(global::SuperJupiter.Views.DateTimePickerView);
            _typeTable[20] = typeof(global::SuperJupiter.Views.EasingFunctionsView);
            _typeTable[21] = typeof(global::SuperJupiter.Views.EdgeUITransitionView);
            _typeTable[22] = typeof(global::SuperJupiter.Views.EntranceThemeTransitionView);
            _typeTable[23] = typeof(global::SuperJupiter.Views.FlipView);
            _typeTable[24] = typeof(global::SuperJupiter.Views.FlyoutsView);
            _typeTable[25] = typeof(global::System.Boolean);
            _typeTable[26] = typeof(global::SuperJupiter.Views.FocusedElementRemovedView);
            _typeTable[27] = typeof(global::SuperJupiter.Views.FocusEngagementView);
            _typeTable[28] = typeof(global::SuperJupiter.Views.FromToByAnimationsView);
            _typeTable[29] = typeof(global::SuperJupiter.Views.HubView);
            _typeTable[30] = typeof(global::SuperJupiter.Views.ImageView);
            _typeTable[31] = typeof(global::SuperJupiter.Views.KeyFramesAnimationView);
            _typeTable[32] = typeof(global::SuperJupiter.Views.KeyTipsView);
            _typeTable[33] = typeof(global::SuperJupiter.Views.ListViewBaseView);
            _typeTable[34] = typeof(global::SuperJupiter.MainPage);
            _typeTable[35] = typeof(global::SuperJupiter.Views.MapsView);
            _typeTable[36] = typeof(global::SuperJupiter.Views.MediaPlayerView);
            _typeTable[37] = typeof(global::SuperJupiter.Views.MediaView);
            _typeTable[38] = typeof(global::SuperJupiter.Views.MessageDialogView);
            _typeTable[39] = typeof(global::SuperJupiter.Views.PaneThemeTransitionView);
            _typeTable[40] = typeof(global::SuperJupiter.Views.PivotView);
            _typeTable[41] = typeof(global::SuperJupiter.Views.PopupThemeTransitionView);
            _typeTable[42] = typeof(global::SuperJupiter.Views.PopupBaseView);
            _typeTable[43] = typeof(global::SuperJupiter.Views.ProgressView);
            _typeTable[44] = typeof(global::SuperJupiter.Views.RelativeLayoutView);
            _typeTable[45] = typeof(global::SuperJupiter.Views.ReorderThemeTransitionView);
            _typeTable[46] = typeof(global::SuperJupiter.Views.RepositionThemeTransitionView);
            _typeTable[47] = typeof(global::SuperJupiter.Views.ScrollViewerView);
            _typeTable[48] = typeof(global::SuperJupiter.Views.SemanticZoomView);
            _typeTable[49] = typeof(global::SuperJupiter.Views.SlideNavTransitionView);
            _typeTable[50] = typeof(global::SuperJupiter.Views.SplitView);
            _typeTable[51] = typeof(global::SuperJupiter.Views.SuperJupiterHomeView);
            _typeTable[52] = typeof(global::SuperJupiterViews.TestUserControl);
            _typeTable[53] = typeof(global::SuperJupiter.Views.TextBoxView);
            _typeTable[54] = typeof(global::SuperJupiter.Views.TextView);
            _typeTable[55] = typeof(global::SuperJupiter.Views.ThemeAnimationsView);
            _typeTable[56] = typeof(global::SuperJupiter.Views.TooltipView);
            _typeTable[57] = typeof(global::SuperJupiter.Views.TurnstileFeatheringNavTransitionView);
            _typeTable[58] = typeof(global::SuperJupiter.Views.TurnstileNavTransitionView);
            _typeTable[59] = typeof(global::SuperJupiter.Views.WebView);
        }

        private int LookupTypeIndexByName(string typeName)
        {
            if (_typeNameTable == null)
            {
                InitTypeTables();
            }
            for (int i=0; i<_typeNameTable.Length; i++)
            {
                if(0 == string.CompareOrdinal(_typeNameTable[i], typeName))
                {
                    return i;
                }
            }
            return -1;
        }

        private int LookupTypeIndexByType(global::System.Type type)
        {
            if (_typeTable == null)
            {
                InitTypeTables();
            }
            for(int i=0; i<_typeTable.Length; i++)
            {
                if(type == _typeTable[i])
                {
                    return i;
                }
            }
            return -1;
        }

        private object Activate_0_AddDeleteView() { return new global::SuperJupiter.Views.AddDeleteView(); }
        private object Activate_3_AnimationsView() { return new global::SuperJupiter.Views.AnimationsView(); }
        private object Activate_4_AutoFocusTrapsView() { return new global::SuperJupiter.Views.AutoFocusTrapsView(); }
        private object Activate_5_BindingTestView() { return new global::SuperJupiter.Views.BindingTestView(); }
        private object Activate_6_ButtonBaseView() { return new global::SuperJupiter.Views.ButtonBaseView(); }
        private object Activate_7_CalendarPickerView() { return new global::SuperJupiter.Views.CalendarPickerView(); }
        private object Activate_8_CaptureElementView() { return new global::SuperJupiter.Views.CaptureElementView(); }
        private object Activate_9_ColorDoublePointAnimationView() { return new global::SuperJupiter.Views.ColorDoublePointAnimationView(); }
        private object Activate_10_ComboBoxView() { return new global::SuperJupiter.Views.ComboBoxView(); }
        private object Activate_11_CommandBarView() { return new global::SuperJupiter.Views.CommandBarView(); }
        private object Activate_12_ContentDialogView() { return new global::SuperJupiter.Views.ContentDialogView(); }
        private object Activate_13_ContentThemeTransitionView() { return new global::SuperJupiter.Views.ContentThemeTransitionView(); }
        private object Activate_14_ContinuumNavTransitionView() { return new global::SuperJupiter.Views.ContinuumNavTransitionView(); }
        private object Activate_15_List() { return new global::System.Collections.Generic.List<global::System.String>(); }
        private object Activate_18_ControlAnimationsView() { return new global::SuperJupiter.Views.ControlAnimationsView(); }
        private object Activate_19_DateTimePickerView() { return new global::SuperJupiter.Views.DateTimePickerView(); }
        private object Activate_20_EasingFunctionsView() { return new global::SuperJupiter.Views.EasingFunctionsView(); }
        private object Activate_21_EdgeUITransitionView() { return new global::SuperJupiter.Views.EdgeUITransitionView(); }
        private object Activate_22_EntranceThemeTransitionView() { return new global::SuperJupiter.Views.EntranceThemeTransitionView(); }
        private object Activate_23_FlipView() { return new global::SuperJupiter.Views.FlipView(); }
        private object Activate_24_FlyoutsView() { return new global::SuperJupiter.Views.FlyoutsView(); }
        private object Activate_26_FocusedElementRemovedView() { return new global::SuperJupiter.Views.FocusedElementRemovedView(); }
        private object Activate_27_FocusEngagementView() { return new global::SuperJupiter.Views.FocusEngagementView(); }
        private object Activate_28_FromToByAnimationsView() { return new global::SuperJupiter.Views.FromToByAnimationsView(); }
        private object Activate_29_HubView() { return new global::SuperJupiter.Views.HubView(); }
        private object Activate_30_ImageView() { return new global::SuperJupiter.Views.ImageView(); }
        private object Activate_31_KeyFramesAnimationView() { return new global::SuperJupiter.Views.KeyFramesAnimationView(); }
        private object Activate_32_KeyTipsView() { return new global::SuperJupiter.Views.KeyTipsView(); }
        private object Activate_33_ListViewBaseView() { return new global::SuperJupiter.Views.ListViewBaseView(); }
        private object Activate_34_MainPage() { return new global::SuperJupiter.MainPage(); }
        private object Activate_35_MapsView() { return new global::SuperJupiter.Views.MapsView(); }
        private object Activate_36_MediaPlayerView() { return new global::SuperJupiter.Views.MediaPlayerView(); }
        private object Activate_37_MediaView() { return new global::SuperJupiter.Views.MediaView(); }
        private object Activate_38_MessageDialogView() { return new global::SuperJupiter.Views.MessageDialogView(); }
        private object Activate_39_PaneThemeTransitionView() { return new global::SuperJupiter.Views.PaneThemeTransitionView(); }
        private object Activate_40_PivotView() { return new global::SuperJupiter.Views.PivotView(); }
        private object Activate_41_PopupThemeTransitionView() { return new global::SuperJupiter.Views.PopupThemeTransitionView(); }
        private object Activate_42_PopupBaseView() { return new global::SuperJupiter.Views.PopupBaseView(); }
        private object Activate_43_ProgressView() { return new global::SuperJupiter.Views.ProgressView(); }
        private object Activate_44_RelativeLayoutView() { return new global::SuperJupiter.Views.RelativeLayoutView(); }
        private object Activate_45_ReorderThemeTransitionView() { return new global::SuperJupiter.Views.ReorderThemeTransitionView(); }
        private object Activate_46_RepositionThemeTransitionView() { return new global::SuperJupiter.Views.RepositionThemeTransitionView(); }
        private object Activate_47_ScrollViewerView() { return new global::SuperJupiter.Views.ScrollViewerView(); }
        private object Activate_48_SemanticZoomView() { return new global::SuperJupiter.Views.SemanticZoomView(); }
        private object Activate_49_SlideNavTransitionView() { return new global::SuperJupiter.Views.SlideNavTransitionView(); }
        private object Activate_50_SplitView() { return new global::SuperJupiter.Views.SplitView(); }
        private object Activate_51_SuperJupiterHomeView() { return new global::SuperJupiter.Views.SuperJupiterHomeView(); }
        private object Activate_52_TestUserControl() { return new global::SuperJupiterViews.TestUserControl(); }
        private object Activate_53_TextBoxView() { return new global::SuperJupiter.Views.TextBoxView(); }
        private object Activate_54_TextView() { return new global::SuperJupiter.Views.TextView(); }
        private object Activate_55_ThemeAnimationsView() { return new global::SuperJupiter.Views.ThemeAnimationsView(); }
        private object Activate_56_TooltipView() { return new global::SuperJupiter.Views.TooltipView(); }
        private object Activate_57_TurnstileFeatheringNavTransitionView() { return new global::SuperJupiter.Views.TurnstileFeatheringNavTransitionView(); }
        private object Activate_58_TurnstileNavTransitionView() { return new global::SuperJupiter.Views.TurnstileNavTransitionView(); }
        private object Activate_59_WebView() { return new global::SuperJupiter.Views.WebView(); }
        private void VectorAdd_15_List(object instance, object item)
        {
            var collection = (global::System.Collections.Generic.ICollection<global::System.String>)instance;
            var newItem = (global::System.String)item;
            collection.Add(newItem);
        }

        private global::Windows.UI.Xaml.Markup.IXamlType CreateXamlType(int typeIndex)
        {
            global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlSystemBaseType xamlType = null;
            global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType userType;
            string typeName = _typeNameTable[typeIndex];
            global::System.Type type = _typeTable[typeIndex];

            switch (typeIndex)
            {

            case 0:   //  SuperJupiter.Views.AddDeleteView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_0_AddDeleteView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 1:   //  Windows.UI.Xaml.Controls.Page
                xamlType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlSystemBaseType(typeName, type);
                break;

            case 2:   //  Windows.UI.Xaml.Controls.UserControl
                xamlType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlSystemBaseType(typeName, type);
                break;

            case 3:   //  SuperJupiter.Views.AnimationsView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_3_AnimationsView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 4:   //  SuperJupiter.Views.AutoFocusTrapsView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_4_AutoFocusTrapsView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 5:   //  SuperJupiter.Views.BindingTestView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_5_BindingTestView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 6:   //  SuperJupiter.Views.ButtonBaseView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_6_ButtonBaseView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 7:   //  SuperJupiter.Views.CalendarPickerView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_7_CalendarPickerView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 8:   //  SuperJupiter.Views.CaptureElementView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_8_CaptureElementView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 9:   //  SuperJupiter.Views.ColorDoublePointAnimationView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_9_ColorDoublePointAnimationView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 10:   //  SuperJupiter.Views.ComboBoxView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_10_ComboBoxView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 11:   //  SuperJupiter.Views.CommandBarView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_11_CommandBarView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 12:   //  SuperJupiter.Views.ContentDialogView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_12_ContentDialogView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 13:   //  SuperJupiter.Views.ContentThemeTransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_13_ContentThemeTransitionView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 14:   //  SuperJupiter.Views.ContinuumNavTransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_14_ContinuumNavTransitionView;
                userType.AddMemberName("Items");
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 15:   //  System.Collections.Generic.List`1<String>
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Object"));
                userType.CollectionAdd = VectorAdd_15_List;
                userType.SetIsReturnTypeStub();
                xamlType = userType;
                break;

            case 16:   //  Object
                xamlType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlSystemBaseType(typeName, type);
                break;

            case 17:   //  String
                xamlType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlSystemBaseType(typeName, type);
                break;

            case 18:   //  SuperJupiter.Views.ControlAnimationsView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_18_ControlAnimationsView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 19:   //  SuperJupiter.Views.DateTimePickerView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_19_DateTimePickerView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 20:   //  SuperJupiter.Views.EasingFunctionsView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_20_EasingFunctionsView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 21:   //  SuperJupiter.Views.EdgeUITransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_21_EdgeUITransitionView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 22:   //  SuperJupiter.Views.EntranceThemeTransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_22_EntranceThemeTransitionView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 23:   //  SuperJupiter.Views.FlipView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_23_FlipView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 24:   //  SuperJupiter.Views.FlyoutsView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_24_FlyoutsView;
                userType.AddMemberName("IsShuffleEnabled");
                userType.AddMemberName("IsRepeatEnabled");
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 25:   //  Boolean
                xamlType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlSystemBaseType(typeName, type);
                break;

            case 26:   //  SuperJupiter.Views.FocusedElementRemovedView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_26_FocusedElementRemovedView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 27:   //  SuperJupiter.Views.FocusEngagementView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_27_FocusEngagementView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 28:   //  SuperJupiter.Views.FromToByAnimationsView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_28_FromToByAnimationsView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 29:   //  SuperJupiter.Views.HubView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_29_HubView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 30:   //  SuperJupiter.Views.ImageView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_30_ImageView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 31:   //  SuperJupiter.Views.KeyFramesAnimationView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_31_KeyFramesAnimationView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 32:   //  SuperJupiter.Views.KeyTipsView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_32_KeyTipsView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 33:   //  SuperJupiter.Views.ListViewBaseView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_33_ListViewBaseView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 34:   //  SuperJupiter.MainPage
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_34_MainPage;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 35:   //  SuperJupiter.Views.MapsView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_35_MapsView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 36:   //  SuperJupiter.Views.MediaPlayerView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_36_MediaPlayerView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 37:   //  SuperJupiter.Views.MediaView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_37_MediaView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 38:   //  SuperJupiter.Views.MessageDialogView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_38_MessageDialogView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 39:   //  SuperJupiter.Views.PaneThemeTransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_39_PaneThemeTransitionView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 40:   //  SuperJupiter.Views.PivotView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_40_PivotView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 41:   //  SuperJupiter.Views.PopupThemeTransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_41_PopupThemeTransitionView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 42:   //  SuperJupiter.Views.PopupBaseView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_42_PopupBaseView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 43:   //  SuperJupiter.Views.ProgressView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_43_ProgressView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 44:   //  SuperJupiter.Views.RelativeLayoutView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_44_RelativeLayoutView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 45:   //  SuperJupiter.Views.ReorderThemeTransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_45_ReorderThemeTransitionView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 46:   //  SuperJupiter.Views.RepositionThemeTransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_46_RepositionThemeTransitionView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 47:   //  SuperJupiter.Views.ScrollViewerView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_47_ScrollViewerView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 48:   //  SuperJupiter.Views.SemanticZoomView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_48_SemanticZoomView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 49:   //  SuperJupiter.Views.SlideNavTransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_49_SlideNavTransitionView;
                userType.AddMemberName("Items");
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 50:   //  SuperJupiter.Views.SplitView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_50_SplitView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 51:   //  SuperJupiter.Views.SuperJupiterHomeView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_51_SuperJupiterHomeView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 52:   //  SuperJupiterViews.TestUserControl
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.UserControl"));
                userType.Activator = Activate_52_TestUserControl;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 53:   //  SuperJupiter.Views.TextBoxView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_53_TextBoxView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 54:   //  SuperJupiter.Views.TextView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_54_TextView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 55:   //  SuperJupiter.Views.ThemeAnimationsView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_55_ThemeAnimationsView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 56:   //  SuperJupiter.Views.TooltipView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_56_TooltipView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 57:   //  SuperJupiter.Views.TurnstileFeatheringNavTransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_57_TurnstileFeatheringNavTransitionView;
                userType.AddMemberName("Items");
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 58:   //  SuperJupiter.Views.TurnstileNavTransitionView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_58_TurnstileNavTransitionView;
                userType.AddMemberName("Items");
                userType.SetIsLocalType();
                xamlType = userType;
                break;

            case 59:   //  SuperJupiter.Views.WebView
                userType = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("Windows.UI.Xaml.Controls.Page"));
                userType.Activator = Activate_59_WebView;
                userType.SetIsLocalType();
                xamlType = userType;
                break;
            }
            return xamlType;
        }


        private object get_0_ContinuumNavTransitionView_Items(object instance)
        {
            var that = (global::SuperJupiter.Views.ContinuumNavTransitionView)instance;
            return that.Items;
        }
        private void set_0_ContinuumNavTransitionView_Items(object instance, object Value)
        {
            var that = (global::SuperJupiter.Views.ContinuumNavTransitionView)instance;
            that.Items = (global::System.Collections.Generic.List<global::System.String>)Value;
        }
        private object get_1_FlyoutsView_IsShuffleEnabled(object instance)
        {
            var that = (global::SuperJupiter.Views.FlyoutsView)instance;
            return that.IsShuffleEnabled;
        }
        private void set_1_FlyoutsView_IsShuffleEnabled(object instance, object Value)
        {
            var that = (global::SuperJupiter.Views.FlyoutsView)instance;
            that.IsShuffleEnabled = (global::System.Boolean)Value;
        }
        private object get_2_FlyoutsView_IsRepeatEnabled(object instance)
        {
            var that = (global::SuperJupiter.Views.FlyoutsView)instance;
            return that.IsRepeatEnabled;
        }
        private void set_2_FlyoutsView_IsRepeatEnabled(object instance, object Value)
        {
            var that = (global::SuperJupiter.Views.FlyoutsView)instance;
            that.IsRepeatEnabled = (global::System.Boolean)Value;
        }
        private object get_3_SlideNavTransitionView_Items(object instance)
        {
            var that = (global::SuperJupiter.Views.SlideNavTransitionView)instance;
            return that.Items;
        }
        private void set_3_SlideNavTransitionView_Items(object instance, object Value)
        {
            var that = (global::SuperJupiter.Views.SlideNavTransitionView)instance;
            that.Items = (global::System.Collections.Generic.List<global::System.String>)Value;
        }
        private object get_4_TurnstileFeatheringNavTransitionView_Items(object instance)
        {
            var that = (global::SuperJupiter.Views.TurnstileFeatheringNavTransitionView)instance;
            return that.Items;
        }
        private void set_4_TurnstileFeatheringNavTransitionView_Items(object instance, object Value)
        {
            var that = (global::SuperJupiter.Views.TurnstileFeatheringNavTransitionView)instance;
            that.Items = (global::System.Collections.Generic.List<global::System.String>)Value;
        }
        private object get_5_TurnstileNavTransitionView_Items(object instance)
        {
            var that = (global::SuperJupiter.Views.TurnstileNavTransitionView)instance;
            return that.Items;
        }
        private void set_5_TurnstileNavTransitionView_Items(object instance, object Value)
        {
            var that = (global::SuperJupiter.Views.TurnstileNavTransitionView)instance;
            that.Items = (global::System.Collections.Generic.List<global::System.String>)Value;
        }

        private global::Windows.UI.Xaml.Markup.IXamlMember CreateXamlMember(string longMemberName)
        {
            global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlMember xamlMember = null;
            global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType userType;

            switch (longMemberName)
            {
            case "SuperJupiter.Views.ContinuumNavTransitionView.Items":
                userType = (global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType)GetXamlTypeByName("SuperJupiter.Views.ContinuumNavTransitionView");
                xamlMember = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlMember(this, "Items", "System.Collections.Generic.List`1<String>");
                xamlMember.Getter = get_0_ContinuumNavTransitionView_Items;
                xamlMember.Setter = set_0_ContinuumNavTransitionView_Items;
                break;
            case "SuperJupiter.Views.FlyoutsView.IsShuffleEnabled":
                userType = (global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType)GetXamlTypeByName("SuperJupiter.Views.FlyoutsView");
                xamlMember = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlMember(this, "IsShuffleEnabled", "Boolean");
                xamlMember.SetIsDependencyProperty();
                xamlMember.Getter = get_1_FlyoutsView_IsShuffleEnabled;
                xamlMember.Setter = set_1_FlyoutsView_IsShuffleEnabled;
                break;
            case "SuperJupiter.Views.FlyoutsView.IsRepeatEnabled":
                userType = (global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType)GetXamlTypeByName("SuperJupiter.Views.FlyoutsView");
                xamlMember = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlMember(this, "IsRepeatEnabled", "Boolean");
                xamlMember.SetIsDependencyProperty();
                xamlMember.Getter = get_2_FlyoutsView_IsRepeatEnabled;
                xamlMember.Setter = set_2_FlyoutsView_IsRepeatEnabled;
                break;
            case "SuperJupiter.Views.SlideNavTransitionView.Items":
                userType = (global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType)GetXamlTypeByName("SuperJupiter.Views.SlideNavTransitionView");
                xamlMember = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlMember(this, "Items", "System.Collections.Generic.List`1<String>");
                xamlMember.Getter = get_3_SlideNavTransitionView_Items;
                xamlMember.Setter = set_3_SlideNavTransitionView_Items;
                break;
            case "SuperJupiter.Views.TurnstileFeatheringNavTransitionView.Items":
                userType = (global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType)GetXamlTypeByName("SuperJupiter.Views.TurnstileFeatheringNavTransitionView");
                xamlMember = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlMember(this, "Items", "System.Collections.Generic.List`1<String>");
                xamlMember.Getter = get_4_TurnstileFeatheringNavTransitionView_Items;
                xamlMember.Setter = set_4_TurnstileFeatheringNavTransitionView_Items;
                break;
            case "SuperJupiter.Views.TurnstileNavTransitionView.Items":
                userType = (global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlUserType)GetXamlTypeByName("SuperJupiter.Views.TurnstileNavTransitionView");
                xamlMember = new global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlMember(this, "Items", "System.Collections.Generic.List`1<String>");
                xamlMember.Getter = get_5_TurnstileNavTransitionView_Items;
                xamlMember.Setter = set_5_TurnstileNavTransitionView_Items;
                break;
            }
            return xamlMember;
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class XamlSystemBaseType : global::Windows.UI.Xaml.Markup.IXamlType
    {
        string _fullName;
        global::System.Type _underlyingType;

        public XamlSystemBaseType(string fullName, global::System.Type underlyingType)
        {
            _fullName = fullName;
            _underlyingType = underlyingType;
        }

        public string FullName { get { return _fullName; } }

        public global::System.Type UnderlyingType
        {
            get
            {
                return _underlyingType;
            }
        }

        virtual public global::Windows.UI.Xaml.Markup.IXamlType BaseType { get { throw new global::System.NotImplementedException(); } }
        virtual public global::Windows.UI.Xaml.Markup.IXamlMember ContentProperty { get { throw new global::System.NotImplementedException(); } }
        virtual public global::Windows.UI.Xaml.Markup.IXamlMember GetMember(string name) { throw new global::System.NotImplementedException(); }
        virtual public bool IsArray { get { throw new global::System.NotImplementedException(); } }
        virtual public bool IsCollection { get { throw new global::System.NotImplementedException(); } }
        virtual public bool IsConstructible { get { throw new global::System.NotImplementedException(); } }
        virtual public bool IsDictionary { get { throw new global::System.NotImplementedException(); } }
        virtual public bool IsMarkupExtension { get { throw new global::System.NotImplementedException(); } }
        virtual public bool IsBindable { get { throw new global::System.NotImplementedException(); } }
        virtual public bool IsReturnTypeStub { get { throw new global::System.NotImplementedException(); } }
        virtual public bool IsLocalType { get { throw new global::System.NotImplementedException(); } }
        virtual public global::Windows.UI.Xaml.Markup.IXamlType ItemType { get { throw new global::System.NotImplementedException(); } }
        virtual public global::Windows.UI.Xaml.Markup.IXamlType KeyType { get { throw new global::System.NotImplementedException(); } }
        virtual public object ActivateInstance() { throw new global::System.NotImplementedException(); }
        virtual public void AddToMap(object instance, object key, object item)  { throw new global::System.NotImplementedException(); }
        virtual public void AddToVector(object instance, object item)  { throw new global::System.NotImplementedException(); }
        virtual public void RunInitializer()   { throw new global::System.NotImplementedException(); }
        virtual public object CreateFromString(string input)   { throw new global::System.NotImplementedException(); }
    }
    
    internal delegate object Activator();
    internal delegate void AddToCollection(object instance, object item);
    internal delegate void AddToDictionary(object instance, object key, object item);
    internal delegate object CreateFromStringMethod(string args);

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class XamlUserType : global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlSystemBaseType
    {
        global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlTypeInfoProvider _provider;
        global::Windows.UI.Xaml.Markup.IXamlType _baseType;
        bool _isArray;
        bool _isMarkupExtension;
        bool _isBindable;
        bool _isReturnTypeStub;
        bool _isLocalType;

        string _contentPropertyName;
        string _itemTypeName;
        string _keyTypeName;
        global::System.Collections.Generic.Dictionary<string, string> _memberNames;
        global::System.Collections.Generic.Dictionary<string, object> _enumValues;

        public XamlUserType(global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlTypeInfoProvider provider, string fullName, global::System.Type fullType, global::Windows.UI.Xaml.Markup.IXamlType baseType)
            :base(fullName, fullType)
        {
            _provider = provider;
            _baseType = baseType;
        }

        // --- Interface methods ----

        override public global::Windows.UI.Xaml.Markup.IXamlType BaseType { get { return _baseType; } }
        override public bool IsArray { get { return _isArray; } }
        override public bool IsCollection { get { return (CollectionAdd != null); } }
        override public bool IsConstructible { get { return (Activator != null); } }
        override public bool IsDictionary { get { return (DictionaryAdd != null); } }
        override public bool IsMarkupExtension { get { return _isMarkupExtension; } }
        override public bool IsBindable { get { return _isBindable; } }
        override public bool IsReturnTypeStub { get { return _isReturnTypeStub; } }
        override public bool IsLocalType { get { return _isLocalType; } }

        override public global::Windows.UI.Xaml.Markup.IXamlMember ContentProperty
        {
            get { return _provider.GetMemberByLongName(_contentPropertyName); }
        }

        override public global::Windows.UI.Xaml.Markup.IXamlType ItemType
        {
            get { return _provider.GetXamlTypeByName(_itemTypeName); }
        }

        override public global::Windows.UI.Xaml.Markup.IXamlType KeyType
        {
            get { return _provider.GetXamlTypeByName(_keyTypeName); }
        }

        override public global::Windows.UI.Xaml.Markup.IXamlMember GetMember(string name)
        {
            if (_memberNames == null)
            {
                return null;
            }
            string longName;
            if (_memberNames.TryGetValue(name, out longName))
            {
                return _provider.GetMemberByLongName(longName);
            }
            return null;
        }

        override public object ActivateInstance()
        {
            return Activator(); 
        }

        override public void AddToMap(object instance, object key, object item) 
        {
            DictionaryAdd(instance, key, item);
        }

        override public void AddToVector(object instance, object item)
        {
            CollectionAdd(instance, item);
        }

        override public void RunInitializer() 
        {
            global::System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(UnderlyingType.TypeHandle);
        }

        override public object CreateFromString(string input)
        {
            if (CreateFromStringMethod != null)
            {
                return this.CreateFromStringMethod(input);
            }
            else if (_enumValues != null)
            {
                int value = 0;

                string[] valueParts = input.Split(',');

                foreach (string valuePart in valueParts) 
                {
                    object partValue;
                    int enumFieldValue = 0;
                    try
                    {
                        if (_enumValues.TryGetValue(valuePart.Trim(), out partValue))
                        {
                            enumFieldValue = global::System.Convert.ToInt32(partValue);
                        }
                        else
                        {
                            try
                            {
                                enumFieldValue = global::System.Convert.ToInt32(valuePart.Trim());
                            }
                            catch( global::System.FormatException )
                            {
                                foreach( string key in _enumValues.Keys )
                                {
                                    if( string.Compare(valuePart.Trim(), key, global::System.StringComparison.OrdinalIgnoreCase) == 0 )
                                    {
                                        if( _enumValues.TryGetValue(key.Trim(), out partValue) )
                                        {
                                            enumFieldValue = global::System.Convert.ToInt32(partValue);
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                        value |= enumFieldValue; 
                    }
                    catch( global::System.FormatException )
                    {
                        throw new global::System.ArgumentException(input, FullName);
                    }
                }

                return value; 
            }
            throw new global::System.ArgumentException(input, FullName);
        }

        // --- End of Interface methods

        public Activator Activator { get; set; }
        public AddToCollection CollectionAdd { get; set; }
        public AddToDictionary DictionaryAdd { get; set; }
        public CreateFromStringMethod CreateFromStringMethod {get; set; }

        public void SetContentPropertyName(string contentPropertyName)
        {
            _contentPropertyName = contentPropertyName;
        }

        public void SetIsArray()
        {
            _isArray = true; 
        }

        public void SetIsMarkupExtension()
        {
            _isMarkupExtension = true;
        }

        public void SetIsBindable()
        {
            _isBindable = true;
        }

        public void SetIsReturnTypeStub()
        {
            _isReturnTypeStub = true;
        }

        public void SetIsLocalType()
        {
            _isLocalType = true;
        }

        public void SetItemTypeName(string itemTypeName)
        {
            _itemTypeName = itemTypeName;
        }

        public void SetKeyTypeName(string keyTypeName)
        {
            _keyTypeName = keyTypeName;
        }

        public void AddMemberName(string shortName)
        {
            if(_memberNames == null)
            {
                _memberNames =  new global::System.Collections.Generic.Dictionary<string,string>();
            }
            _memberNames.Add(shortName, FullName + "." + shortName);
        }

        public void AddEnumValue(string name, object value)
        {
            if (_enumValues == null)
            {
                _enumValues = new global::System.Collections.Generic.Dictionary<string, object>();
            }
            _enumValues.Add(name, value);
        }
    }

    internal delegate object Getter(object instance);
    internal delegate void Setter(object instance, object value);

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.16.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class XamlMember : global::Windows.UI.Xaml.Markup.IXamlMember
    {
        global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlTypeInfoProvider _provider;
        string _name;
        bool _isAttachable;
        bool _isDependencyProperty;
        bool _isReadOnly;

        string _typeName;
        string _targetTypeName;

        public XamlMember(global::SuperJupiterViews.SuperJupiterViews_XamlTypeInfo.XamlTypeInfoProvider provider, string name, string typeName)
        {
            _name = name;
            _typeName = typeName;
            _provider = provider;
        }

        public string Name { get { return _name; } }

        public global::Windows.UI.Xaml.Markup.IXamlType Type
        {
            get { return _provider.GetXamlTypeByName(_typeName); }
        }

        public void SetTargetTypeName(string targetTypeName)
        {
            _targetTypeName = targetTypeName;
        }
        public global::Windows.UI.Xaml.Markup.IXamlType TargetType
        {
            get { return _provider.GetXamlTypeByName(_targetTypeName); }
        }

        public void SetIsAttachable() { _isAttachable = true; }
        public bool IsAttachable { get { return _isAttachable; } }

        public void SetIsDependencyProperty() { _isDependencyProperty = true; }
        public bool IsDependencyProperty { get { return _isDependencyProperty; } }

        public void SetIsReadOnly() { _isReadOnly = true; }
        public bool IsReadOnly { get { return _isReadOnly; } }

        public Getter Getter { get; set; }
        public object GetValue(object instance)
        {
            if (Getter != null)
                return Getter(instance);
            else
                throw new global::System.InvalidOperationException("GetValue");
        }

        public Setter Setter { get; set; }
        public void SetValue(object instance, object value)
        {
            if (Setter != null)
                Setter(instance, value);
            else
                throw new global::System.InvalidOperationException("SetValue");
        }
    }
}

